### ISSUE TITLE
Gripper not moving

### ISSUE THREAD

**Issue by TimAdamson21** [gt-ros-pkg/hrl-assistive#13]
When I try to move the grippers, I am getting the following error. I have been unsuccessful at finding the node in the code base so far. 

/r_gripper_sensor_controller/grab_action_node ServerGoalHandle<ActionSpec>::setCanceled:116: To transition to a cancelled state, the goal must be in a pending, recalling, active, or preempting state, it is currently in state: 2

**Comment by pgrice** [comment]
That error is from actionlib, ultimately, via the pr2_gripper_sensor/grab_action_node. The interface uses the pr2_gripper_sensor_action suite to control the gripper (http://wiki.ros.org/pr2_gripper_sensor_action).  Any command to close the gripper starts a 'grab' action, using the pr2_gripper_sensor_action nodes to try to gently grab any item in the gripper.  Opening the gripper at all will interrupt the grab action and use a gripper_action call to open the grippers all the way.

I don't modify the pr2_gripper_senor_action content at all (it's installed from debs via apt), and it seems like the issue is in there, so I'm not sure I can provide much more specific guidance, other than I don't think I see this error, or if I do, it doesn't change the behavior and I've just ignored it. You might make sure the pressure sensors are installed on the PR2's fingertips, since the sensor_action uses those, and it might be causing problems if they're not present.  Otherwise, you might try to create a minimal example, and/or post to ROS Answers.
